### ISSUE TITLE
Python plugin 'binja-retdec' could not be loaded

### ISSUE THREAD

**Issue by AddaxSoft** [hugsy/binja-retdec#8] opened 2017-12-28 17:07 UTC
# OS Version
Windows 10

# Python
I have both: 3.6 & 2.7

# Binary Ninja
Version 1.1.989 Personal (2017-11-07 06:25:32)

# Error messages:

```
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\Binary Ninja\plugins\binja-retdec\__init__.py", line 12, in <module>
  File "C:\Users\xxxx\AppData\Roaming\Binary Ninja\plugins\binja-retdec\retdec.py", line 9, in <module>
    import requests
ImportError: No module named requests
Python plugin 'binja-retdec' could not be loaded
```

I did run:
```
pip install requests
pip3 install requests
pip3 install pygments
pip install pygments
```

output:

```
C:\Users\xxxx>pip install pygments
Requirement already satisfied: pygments in c:\python27\lib\site-packages

C:\Users\xxxx>pip install requests
Requirement already satisfied: requests in c:\python27\lib\site-packages
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\python27\lib\site-packages (from requests)
Requirement already satisfied: idna<2.7,>=2.5 in c:\python27\lib\site-packages (from requests)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python27\lib\site-packages (from requests)
Requirement already satisfied: certifi>=2017.4.17 in c:\python27\lib\site-packages (from requests)
```

**Comment by hugsy** [comment] 2017-12-28 20:05
This is not a bug related to the tool but to your setup.
Try importing `requests` from Binja Python interpreter. If it fails, then post it as a binary-ninja issue. 

Thanks.

**Comment by AddaxSoft** [comment] 2017-12-30 13:02
@hugsy thanks for your reply; I've tried that and it does fail indeed.
Do you happen to know what's the difference between the python interpreter the OS offers and the one inside Binary Ninja?

ps: I've already opened a ticket for support regarding this issue.

**Comment by hugsy** [comment] 2017-12-30 18:25
I really don't know tbh. From inside binja, you can always try to install the package by invoking `pip` from the embedded Python interpreter like this:

```python
>>> import pip
>>> pip.main(['install', "requests"])
```

Not sure how it'll turn out though.

Anyway, I'm closing this ticket since it's not an issue of `binja-retdec`.

**Closed as completed by hugsy** 2017-12-30 18:25 UTC

**Comment by AddaxSoft** [comment] 2018-01-06 12:34
I confirm the above solution worked.
